### ISSUE TITLE
error: initializer element is not constant

### ISSUE THREAD

**Issue by jbennettgit** [facebookincubator/cinder#13]
Running #49~18.04.1-Ubuntu SMP Wed Apr 28 23:08:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Building with either configure; make -j or ./oss-build-and-test
....
>> Python/codecs.o
>> Python/marshal.o
>> Python/context.o
>> Python/hamt.o
>> Python/errors.o
In file included from ./Include/pytime.h:6:0,
                 from ./Include/Python.h:85,
                 from Parser/acceler.c:13:
./Include/object.h:520:40: error: initializer element is not constant
 static const Py_ssize_t kImmortalBit = 1L << kImmortalBitPos;
                                        ^~
./Include/object.h:521:49: error: initializer element is not constant
 static const Py_ssize_t kImmortalInitialCount = kImmortalBit;
                                                 ^~~~~~~~~~~~
In file included from ./Include/pytime.h:6:0,
                 from ./Include/Python.h:85,
                 from Parser/node.c:3:
./Include/object.h:520:40: error: initializer element is not constant
 static const Py_ssize_t kImmortalBit = 1L << kImmortalBitPos;
                                        ^~
./Include/object.h:521:49: error: initializer element is not constant
 static const Py_ssize_t kImmortalInitialCount = kImmortalBit;
                                                 ^~~~~~~~~~~~
....

**Comment by aisk** [comment]
I think you need higher version of GCC. I tested gcc10 and it passed the build. (But faild with other problem)

**Comment by jbower-fb** [comment]
@jbennettgit the only environment we're officially supporting is the Docker container setup described in the README, and (for now) this is based on Fedora 32. Hopefully @aisk's suggestion will help, but I'm afraid if you want to use another environment you'll have to work through this yourself.
