### ISSUE TITLE
Outdated instructions in python-build-env?

### ISSUE THREAD

**Issue by mrigankpawagi** [facebookincubator/cinder#136]
static-python doesn't have the `compiler` in the most recent commit. (`compiler.py` is available inside `cinderx` but there are errors in the module if it is forcefully included in `sys.path`). I am referring to [this](https://github.com/facebookincubator/cinder/pkgs/container/cinder%2Fpython-build-env).

**Comment by jbower-fb** [comment]
You are right, those instructions are now out of date and indeed the compiler has moved into the `cinderx/` directory. What are you trying to do though? I don't understand why you need to manually put it in your `sys.path`.

**Comment by mrigankpawagi** [comment]
Thanks for your response, @jbower-fb. I cannot run `./python -m compiler --static module.py`. Is this something I _do not_ need to do anymore?

**Comment by bennn** [comment]
@jbower-fb we just want to use static python, e.g. to run benchmarks like deltablue
https://github.com/facebookincubator/cinder/blob/cinder/3.10/Tools/benchmarks/deltablue_static.py

**Comment by jbower-fb** [comment]
Ah, you now need to run:
```
$ ./python -m cinderx.compiler --static module.py
```

**Comment by mrigankpawagi** [comment]
Thanks a lot @jbower-fb! Should've noticed this! I will close this issue for now.
