### ISSUE TITLE
Missing builtin modules such as math 

### ISSUE THREAD

**Issue by Mng-dev-ai** [facebookincubator/cinder#14]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/random.py", line 41, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'

**Comment by carljm** [comment]
Cinder definitely has a working `math` module :) Judging from the path in your traceback, it seems that you are trying to run a Cinder binary with a `sys.path` that is pointing to the standard library from some other Python installation, and the extension tags for compiled `.so` modules likely won't match, causing this error. Hard to debug exactly why this is without knowing how you've compiled Cinder and exactly how you are running it, but you need to make sure Cinder is using the Cinder standard library, not the standard library from some other Python on your system.
