### ISSUE TITLE
defunct "-X shadowbytecode" referenced by Makefile?

### ISSUE THREAD

**Issue by belm0** [facebookincubator/cinder#20]
I noticed this during a PGO build.  Perhaps "-X shadowbytecode" is a remnant from when shadow bytecode needed to be explicitly enabled?  I don't see a reference to this option in the source code or docs.

https://github.com/facebookincubator/cinder/blob/afb637523d5f0fdd358a047ebe02a0cafa6f3403/Makefile.pre.in#L287

**Comment by jbower-fb** [comment]
Looks dead to me too. I'll put up a PR internally removing it and see if anyone complains.

**Comment by belm0** [comment]
removed in https://github.com/facebookincubator/cinder/commit/601512fbcb7f1e003e13dbac10bfe973786879fc
