### ISSUE TITLE
track python3.8 minor releases

### ISSUE THREAD

**Issue by belm0** [facebookincubator/cinder#38]
Cinder is on 3.8.5, and there have been countless security and bug fixes up until 3.8.11

is it reasonable for the Cinder project to track minor upstream releases?

I suppose trying to rebase locally before a build may have some chance of success, but I haven't tried it.

**Comment by jbower-fb** [comment]
I suspect tracking even minor releases is still quite a pain as our changes are currently quite pervasive.  If you do try it, please let us know how you get on.

Overall this is an issue we're aware of and if nothing else our internal users will be quite unhappy if we start lagging behind major releases which are even more work. So, we do plan to try and make tracking upstream easier. It will probably take a bit of time to make some progress here but hopefully things will start moving within the next 6 months or so.

I'm going to close this specific issue as this should be an ongoing but likely longer-term effort for us for now.

**Comment by belm0** [comment]
Thank you.  It may be helpful to leave the issue open so that interested parties can subscribe to track any progress.
