### ISSUE TITLE
Add type checking of implicit None return

### ISSUE THREAD

**Issue by LuKuangChen** [facebookincubator/cinder#62]
a4a71ae
2021-12-28

### What program did you run?

```python
from typing import Optional

def f(x: Optional[str]) -> str:
    while True:
        if x is None:
            break
        return x

print(f(None))
```

This program borrowed from [`cinder/3.8/Lib/test/test_compiler/test_static/tests.py` L5536](https://github.com/facebookincubator/cinder/blob/8ce22cc3948c41f2e656ac11877875567e505926/Lib/test/test_compiler/test_static/tests.py#L5536). This test is labeled `test_break_condition`.

### What happened?

The program type-checks and prints `None`, although the function `f` is annotated to return a `str`.

### What should have happened?

The program should be rejected by the type checker.

**Comment by carljm** [comment]
Fixed by 8ea180376e9dcbc92f61bc44434c29b15b637383
